name : Fourth workflow-run on push from main branch - pull request approval

on:
    push:
      branches:
        - main


#workflow level env variables  
env:
  WORKLOW_GREETINGS: "Hello from ECSapp-workflow"

jobs: 
  job1:
    env: 
      JOB_GREETINGS: "Hello from job1"
    runs-on: ubuntu-latest
    steps:
      - name: step1-check if terraform is installed safely
        env: 
          STEP_GREETINGS: "Hello from step variable- in job1"
        run: |
          echo "Hello from ${{ env.WORKLOW_GREETINGS }}"
          echo "Hello from ${{ env.JOB_GREETINGS }}"
          echo "Hello from ${{ env.STEP_GREETINGS }}"
          if command -v terraform >/dev/null 2>&1; then
            echo "Terraform is installed"
            terraform version
          else
            echo "Terraform is not installed"
          fi
        
